/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.sammidev;

import com.sammidev.generator.SimpleNameGenerator;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.DisplayNameGeneration;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

@DisplayNameGeneration(SimpleNameGenerator.class)
class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    Calculator calculator = new Calculator(6d,2d);
    Calculator calculator2 = new Calculator(2d,0);

    @Test
    void testAddSuccess() {
        double result = calculator.adding();
        assertEquals(8d,result);
    }

    @Test
    @Disabled("Coming Soon")
    void testDivideSuccess() {
        double result = calculator.division();
        assertEquals(3d,result);
    }

    @Test
    void testDividedError() {
        Exception exception = assertThrows(IllegalArgumentException.class, () -> {
            calculator2.division();
        });
        assertEquals(exception.getMessage(), "can't divide by zero");
    }

    @Test
//    @DisplayName("TEST SUBSTRACTION")
    void testSubstractSuccess() {
        double result = calculator.substraction();
        assertEquals(4d,result);
    }






}